### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by Marzhan03** [antonntheuser/Lab6#1]
1. Комплиятор C# не может создать исполняемый файл (причина на скрине внизу)
![WhatsApp Image 2022-06-04 at 08 22 37](https://user-images.githubusercontent.com/105795928/171985627-0d8ae37a-d913-41d2-8aab-8787a5465c1d.jpeg)

**Comment by antonntheuser** [comment]
Пытаюсь исправить
![image](https://user-images.githubusercontent.com/106433186/171985999-d1572499-e1ab-426f-96b9-62b9c2958afa.png)

**Comment by antonntheuser** [comment]
![image](https://user-images.githubusercontent.com/106433186/171991857-d8d9ab65-a391-4478-bec3-b04667c76b7c.png)
Поправил, теперь должно работать
